
export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT';
export const RESULTS_FETCHED = 'RESULTS_FETCHED';
export const INFINITE_SCROLL_RESULTS_FETCHED = 'INFINITE_SCROLL_RESULTS_FETCHED';
export const REVIEWS_FETCHED = 'REVIEWS_FETCHED';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const TOGGLE_CART = 'TOGGLE_CART';
